import { Alert, Linking, Platform, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import * as WebBrowser from 'expo-web-browser';
import { resetOnboarding, usePremium } from '@app-factory/core';
import { Ionicons } from '@expo/vector-icons';
import { useApp } from '../../src/AppProvider';
import { common,colors } from '../../src/theme';
import { BrandMark } from '../../src/components';
import type { Joint } from '../../src/types';
import { generatePlan } from '../../src/engine';
import { LOCALES, LOCALE_NAME, useFormatDate, useLocale, useT } from '../../src/i18n';

const PRIVACY_URL='https://parphelie.com/ironhale/privacy';const TERMS_URL='https://www.apple.com/legal/internet-services/itunes/dev/stdeula/';
const MANAGE_URL=Platform.select({ios:'https://apps.apple.com/account/subscriptions',android:'https://play.google.com/store/account/subscriptions',default:'https://apps.apple.com/account/subscriptions'})!;
export default function Settings(){const router=useRouter();const {state,update,reset}=useApp();const {isPremium,restore}=usePremium();const profile=state.profile;
  const t=useT();const formatDate=useFormatDate();const [locale,setLocale]=useLocale();
  const onRestore=async()=>{try{const result=await restore();Alert.alert(result.isActive?t.settings.restoreOk:t.settings.restoreNothing);}catch{Alert.alert(t.settings.restoreFailedTitle,t.settings.restoreFailedBody);}};
  const commitProfile=(next:NonNullable<typeof profile>)=>update((s)=>({...s,profile:next,plan:generatePlan(next,s.progress,s.plan[0]?.scheduledAt??s.createdAt,Math.max(s.plan.length,s.history.length+next.daysPerWeek*12))}));
  const toggle=(joint:Joint)=>profile&&commitProfile({...profile,flaggedJoints:profile.flaggedJoints.includes(joint)?profile.flaggedJoints.filter((j)=>j!==joint):[...profile.flaggedJoints,joint]});
  const resetAll=()=>Alert.alert(t.settings.resetTitle,t.settings.resetBody,[{text:t.settings.cancel,style:'cancel'},{text:t.settings.deleteEverything,style:'destructive',onPress:()=>void (async()=>{await reset();await resetOnboarding();router.replace('/onboarding');})}]);
  const rows=[{icon:'refresh-outline',label:t.settings.restore,press:()=>void onRestore()},{icon:'card-outline',label:t.settings.manageSub,press:()=>void Linking.openURL(MANAGE_URL)},{icon:'shield-outline',label:t.settings.privacy,press:()=>void WebBrowser.openBrowserAsync(PRIVACY_URL)},{icon:'document-text-outline',label:t.settings.terms,press:()=>void WebBrowser.openBrowserAsync(TERMS_URL)}] as const;
  return <SafeAreaView style={common.screen} edges={['top']}><ScrollView contentContainerStyle={common.page}><View style={{flexDirection:'row',alignItems:'center',gap:12}}><BrandMark/><View><Text style={common.eyebrow}>IRONHALE</Text><Text style={common.h1}>{t.settings.title}</Text></View></View>
    <View style={[common.card,s.plan]}><View><Text style={s.label}>{t.settings.yourPlan}</Text><Text style={s.planName}>{isPremium?t.settings.premiumPlan:t.settings.freePlan}</Text></View>{!isPremium?<TouchableOpacity style={s.upgrade} onPress={()=>router.push({pathname:'/paywall',params:{placement:'settings'}})}><Text style={s.upgradeText}>{t.settings.goPremium}</Text></TouchableOpacity>:<Ionicons name="checkmark-circle" size={30} color={colors.green}/>}</View>
    <View><Text style={s.section}>{t.settings.sensitiveJoints}</Text><Text style={[common.body,{fontSize:15,marginBottom:10}]}>{t.settings.sensitiveJointsBody}</Text><View style={s.chips}>{(Object.keys(t.joints) as Joint[]).map((j)=>{const selected=profile?.flaggedJoints.includes(j);return <TouchableOpacity key={j} style={[s.chip,selected&&s.chipActive]} onPress={()=>toggle(j)}><Text style={[s.chipText,selected&&s.chipTextActive]}>{selected?'✓ ':''}{t.joints[j]}</Text></TouchableOpacity>})}</View></View>
    {profile?.temporaryFlags.filter((f)=>f.expiresAt>Date.now()).map((flag)=><View key={flag.joint} style={s.checkin}><View style={{flex:1}}><Text style={s.checkinTitle}>{t.settings.checkin(flag.joint)}</Text><Text style={s.checkinBody}>{t.settings.protectedUntil(formatDate(flag.expiresAt,{month:'short',day:'numeric'}))}</Text></View><TouchableOpacity onPress={()=>commitProfile({...profile,flaggedJoints:[...new Set([...profile.flaggedJoints,flag.joint])],temporaryFlags:profile.temporaryFlags.filter((f)=>f.joint!==flag.joint)})}><Text style={s.permanent}>{t.settings.makePermanent}</Text></TouchableOpacity></View>)}
    {profile?.temporaryFlags.filter((f)=>f.expiresAt<=Date.now()).map((flag)=><View key={`expired-${flag.joint}`} style={[s.checkin,{flexDirection:'column',alignItems:'stretch'}]}><Text style={s.checkinTitle}>{t.settings.feelingBetter(flag.joint)}</Text><View style={s.checkActions}><TouchableOpacity style={s.checkButton} onPress={()=>commitProfile({...profile,temporaryFlags:profile.temporaryFlags.filter((f)=>f.joint!==flag.joint)})}><Text style={s.checkButtonText}>{t.settings.yes}</Text></TouchableOpacity><TouchableOpacity style={s.checkButton} onPress={()=>commitProfile({...profile,temporaryFlags:profile.temporaryFlags.map((f)=>f.joint===flag.joint?{...f,expiresAt:Date.now()+7*86400000}:f)})}><Text style={s.checkButtonText}>{t.settings.stillABit}</Text></TouchableOpacity><TouchableOpacity style={s.checkButton} onPress={()=>commitProfile({...profile,flaggedJoints:[...new Set([...profile.flaggedJoints,flag.joint])],temporaryFlags:profile.temporaryFlags.filter((f)=>f.joint!==flag.joint)})}><Text style={s.checkButtonText}>{t.settings.permanent}</Text></TouchableOpacity></View></View>)}
    <View><Text style={s.section}>{t.settings.language.toUpperCase()}</Text><View style={s.chips}>{LOCALES.map((loc)=>{const active=loc===locale;return <TouchableOpacity key={loc} accessibilityRole="button" accessibilityState={{selected:active}} style={[s.chip,active&&s.chipActive]} onPress={()=>setLocale(loc)}><Text style={[s.chipText,active&&s.chipTextActive]}>{active?'✓ ':''}{LOCALE_NAME[loc]}</Text></TouchableOpacity>})}</View></View>
    <View><Text style={s.section}>{t.settings.units.toUpperCase()}</Text><View style={s.chips}>{(['kg','lb'] as const).map((unit)=>{const active=state.unitSystem===unit;return <TouchableOpacity key={unit} accessibilityRole="button" accessibilityState={{selected:active}} style={[s.chip,active&&s.chipActive]} onPress={()=>update((current)=>({...current,unitSystem:unit}))}><Text style={[s.chipText,active&&s.chipTextActive]}>{active?'✓ ':''}{unit.toUpperCase()}</Text></TouchableOpacity>})}</View></View>
    <View><Text style={s.section}>{t.settings.restDuration.toUpperCase()}</Text><View style={s.chips}>{([60,90,120] as const).map((seconds)=>{const active=state.restSeconds===seconds;return <TouchableOpacity key={seconds} accessibilityRole="button" accessibilityState={{selected:active}} style={[s.chip,active&&s.chipActive]} onPress={()=>update((current)=>({...current,restSeconds:seconds}))}><Text style={[s.chipText,active&&s.chipTextActive]}>{active?'✓ ':''}{seconds}s</Text></TouchableOpacity>})}</View></View>
    <View style={s.group}>{rows.map((row)=><TouchableOpacity key={row.label} style={s.row} onPress={row.press}><Ionicons name={row.icon} size={20} color={colors.green}/><Text style={s.rowText}>{row.label}</Text><Ionicons name="chevron-forward" size={18} color={colors.muted}/></TouchableOpacity>)}</View>
    <View style={s.disclaimer}><Ionicons name="medical-outline" size={21} color={colors.orange}/><Text style={s.disclaimerText}>{t.settings.disclaimer}</Text></View>
    <TouchableOpacity style={s.reset} onPress={resetAll}><Text style={s.resetText}>{t.settings.reset}</Text></TouchableOpacity><Text style={s.version}>{t.settings.version('1.0.0')}</Text>
  </ScrollView></SafeAreaView>}
const s=StyleSheet.create({plan:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},label:{fontSize:12,fontWeight:'900',letterSpacing:1,color:colors.muted},planName:{fontSize:19,fontWeight:'900',color:colors.ink,marginTop:4},upgrade:{minHeight:44,backgroundColor:colors.green,paddingHorizontal:14,paddingVertical:10,borderRadius:12,justifyContent:'center'},upgradeText:{color:'#fff',fontWeight:'800',fontSize:15},section:{fontSize:13,fontWeight:'900',letterSpacing:1.1,color:colors.ink,marginBottom:6},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{minHeight:44,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,borderRadius:999,paddingHorizontal:14,paddingVertical:10,justifyContent:'center'},chipActive:{backgroundColor:colors.soft,borderColor:colors.green},chipText:{fontSize:15,color:colors.muted,fontWeight:'700'},chipTextActive:{color:colors.green},checkin:{backgroundColor:'#FFF0E3',borderRadius:16,padding:16,flexDirection:'row',alignItems:'center',gap:10},checkinTitle:{fontWeight:'800',fontSize:17,color:colors.ink},checkinBody:{fontSize:14,lineHeight:19,color:colors.muted,marginTop:3},permanent:{fontSize:14,fontWeight:'800',color:colors.green},checkActions:{flexDirection:'row',gap:7},checkButton:{flex:1,minHeight:44,backgroundColor:'#fff',borderRadius:10,paddingVertical:10,alignItems:'center',justifyContent:'center'},checkButtonText:{fontSize:13,fontWeight:'800',color:colors.green},group:{backgroundColor:colors.surface,borderRadius:18,borderWidth:1,borderColor:colors.line,overflow:'hidden'},row:{minHeight:62,paddingHorizontal:16,paddingVertical:8,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.line},rowText:{flex:1,fontSize:16,fontWeight:'700',color:colors.ink},disclaimer:{backgroundColor:'#FFF5EC',borderRadius:16,padding:16,flexDirection:'row',gap:10},disclaimerText:{flex:1,fontSize:14,lineHeight:21,color:'#67462F'},reset:{minHeight:48,padding:14,alignItems:'center',justifyContent:'center'},resetText:{color:colors.danger,fontWeight:'700',fontSize:15},version:{textAlign:'center',fontSize:13,lineHeight:18,color:colors.muted}});
