import { useRouter } from 'expo-router';
import { Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { usePremium } from '@app-factory/core';
import { useApp } from '../../src/AppProvider';
import { EXERCISE_BY_ID } from '../../src/exercises';
import { common,colors } from '../../src/theme';
import { BrandMark, Pill } from '../../src/components';

const dateLabel=(timestamp:number)=>new Intl.DateTimeFormat('en-US',{weekday:'long',month:'short',day:'numeric'}).format(new Date(timestamp));
export default function Today(){
  const router=useRouter();const {state,update}=useApp();const {isPremium}=usePremium();
  const completed=new Set(state.history.map((h)=>h.workoutId)); const workout=state.plan.find((w)=>!completed.has(w.id));
  if(!workout)return <SafeAreaView style={common.screen}><View style={common.page}><Text style={common.h1}>Block complete.</Text><Text style={common.body}>You finished every planned session. That is serious work.</Text></View></SafeAreaView>;
  const freeLeft=Math.max(0,6-state.history.length); const locked=workout.index>=7&&!isPremium;
  const start=()=>locked?router.push({pathname:'/paywall',params:{placement:'session7_gate'}}):router.push({pathname:'/workout/[id]',params:{id:workout.id}});
  const reschedule=()=>Alert.alert('Move this session?','IronHale will shift the remaining recovery windows with it.',[{text:'Keep schedule',style:'cancel'},{text:'Move to tomorrow',onPress:()=>{const tomorrow=Date.now()+86400000;const delta=tomorrow-workout.scheduledAt;update((s)=>({...s,plan:s.plan.map((w)=>w.index>=workout.index?{...w,scheduledAt:w.scheduledAt+delta}:w)}));}}]);
  return <SafeAreaView style={common.screen} edges={['top']}><ScrollView contentContainerStyle={common.page}>
    <View style={s.header}><View style={{flex:1,flexDirection:'row',gap:11,alignItems:'center'}}><BrandMark/><View style={{flex:1}}><Text style={common.eyebrow}>IRONHALE</Text><Text style={[common.h1,{fontSize:28}]}>Ready when you are.</Text></View></View><View style={s.streak}><Text style={s.streakNumber}>{state.history.length}</Text><Text style={s.streakLabel}>DONE</Text></View></View>
    {!isPremium?<View style={s.freeBanner}><Text style={s.freeTitle}>Session {Math.min(workout.index,6)} / 6 free</Text><Text style={s.freeBody}>{freeLeft>0?`${freeLeft} card-free session${freeLeft===1?'':'s'} remaining.`:'Your next progressive session is ready with Premium.'}</Text><View style={s.track}><View style={[s.trackFill,{width:`${Math.min(100,(state.history.length/6)*100)}%`}]} /></View></View>:<Pill>★ PRIME MEMBER</Pill>}
    <View style={s.workoutCard}><View style={s.cardTop}><View><Text style={s.week}>WEEK {workout.week}{workout.isDeload?' · RECOVERY WEEK':''}</Text><Text style={s.title}>{workout.title}</Text><Text style={s.meta}>{dateLabel(workout.scheduledAt)} · {workout.exercises.length} movements · 35–45 min</Text></View><View style={s.number}><Text style={s.numberText}>{workout.index}</Text></View></View>
      <View style={s.list}>{workout.exercises.map((item,i)=>{const e=EXERCISE_BY_ID[item.exerciseId];if(!e)return null;return <View key={`${item.exerciseId}-${i}`} style={s.exercise}><View style={s.order}><Text style={s.orderText}>{i+1}</Text></View><View style={{flex:1}}><Text style={s.exerciseName}>{e.name}</Text><Text style={s.exerciseMeta}>{item.sets} × {item.repMin}–{item.repMax}{item.targetLoadKg?` · ${item.targetLoadKg} kg`:''} · RIR {item.targetRir}</Text>{item.substitutedFrom?<Text style={s.adapted}>Adapted for your {item.substitutionReason}</Text>:null}</View></View>})}</View>
      <TouchableOpacity style={common.button} onPress={start}><Text style={common.buttonText}>{locked?'Unlock session 7':'Start workout'}</Text></TouchableOpacity>
      {isPremium?<TouchableOpacity style={s.reschedule} onPress={reschedule}><Text style={s.rescheduleText}>Can't train today? Reschedule</Text></TouchableOpacity>:null}
    </View>
    <View style={[common.card,{flexDirection:'row',gap:14}]}><View style={s.recoveryIcon}><Text style={{fontSize:22}}>↻</Text></View><View style={{flex:1}}><Text style={{fontWeight:'800',fontSize:16,color:colors.ink}}>Recovery is part of the plan</Text><Text style={[common.body,{fontSize:14,marginTop:3}]}>RIR 2, no failure. Your next demanding pattern gets at least 48 hours.</Text></View></View>
    {state.history.length>0?<View style={{gap:10}}><Text style={common.eyebrow}>HISTORY</Text>{state.history.slice().reverse().slice(0,6).map((result)=>{const planned=state.plan.find((w)=>w.id===result.workoutId);return <View key={result.workoutId} style={[common.card,s.history]}><View><Text style={s.historyTitle}>{planned?.title??`Session ${result.workoutIndex}`}</Text><Text style={s.historyMeta}>{dateLabel(result.completedAt)} · {Math.max(1,Math.round(result.durationSeconds/60))} min</Text></View><View style={s.historyCheck}><Text style={{color:'#fff',fontWeight:'900'}}>✓</Text></View></View>})}</View>:null}
  </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({header:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},streak:{width:54,height:54,borderRadius:16,backgroundColor:colors.ink,alignItems:'center',justifyContent:'center'},streakNumber:{color:colors.lime,fontWeight:'900',fontSize:20},streakLabel:{color:'#fff',fontWeight:'800',fontSize:8,letterSpacing:1},freeBanner:{backgroundColor:'#E3F0C8',borderRadius:18,padding:16},freeTitle:{color:colors.ink,fontSize:16,fontWeight:'900'},freeBody:{color:colors.muted,fontSize:13,marginTop:3},track:{height:7,borderRadius:4,backgroundColor:'#C6D3AE',marginTop:12,overflow:'hidden'},trackFill:{height:7,backgroundColor:colors.green,borderRadius:4},workoutCard:{backgroundColor:colors.ink,borderRadius:24,padding:20,gap:18},cardTop:{flexDirection:'row',justifyContent:'space-between'},week:{color:colors.lime,fontSize:11,fontWeight:'900',letterSpacing:1.2},title:{color:'#fff',fontSize:28,fontWeight:'900',marginTop:4},meta:{color:'#ADB7B0',fontSize:13,marginTop:5},number:{width:42,height:42,borderRadius:21,borderWidth:1,borderColor:'#455149',alignItems:'center',justifyContent:'center'},numberText:{color:'#fff',fontWeight:'900'},list:{gap:15},exercise:{flexDirection:'row',gap:12,alignItems:'center'},order:{width:28,height:28,borderRadius:8,backgroundColor:'#334039',alignItems:'center',justifyContent:'center'},orderText:{color:colors.lime,fontWeight:'900'},exerciseName:{color:'#fff',fontSize:15,fontWeight:'800'},exerciseMeta:{color:'#ADB7B0',fontSize:12,marginTop:2},adapted:{color:colors.lime,fontSize:11,fontWeight:'700',marginTop:3},reschedule:{alignItems:'center',paddingVertical:2},rescheduleText:{color:'#BBC4BE',fontSize:13,fontWeight:'700'},recoveryIcon:{width:44,height:44,borderRadius:14,backgroundColor:colors.soft,alignItems:'center',justifyContent:'center'},history:{padding:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},historyTitle:{fontSize:15,fontWeight:'800',color:colors.ink},historyMeta:{fontSize:12,color:colors.muted,marginTop:3},historyCheck:{width:30,height:30,borderRadius:10,backgroundColor:colors.green,alignItems:'center',justifyContent:'center'}});
