import { useEffect, useMemo } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { usePremium } from '@app-factory/core';
import { useApp } from '../../src/AppProvider';
import { epley } from '../../src/engine';
import { EXERCISE_BY_ID, PATTERN_LABELS } from '../../src/exercises';
import { common,colors } from '../../src/theme';
import type { Pattern } from '../../src/types';

const patterns=Object.keys(PATTERN_LABELS) as Pattern[];
export default function Progress(){
  const router=useRouter();const {isPremium,ready}=usePremium();const {state}=useApp();
  useEffect(()=>{if(ready&&!isPremium)router.push({pathname:'/paywall',params:{placement:'progress_gate'}});},[isPremium,ready,router]);
  const points=useMemo(()=>patterns.map((pattern)=>{const values=state.history.flatMap((workout)=>workout.exercises.filter((r)=>EXERCISE_BY_ID[r.exerciseId]?.pattern===pattern).map((r)=>{const best=r.sets.filter((s)=>s.complete&&s.loadKg>0).map((s)=>epley(s.loadKg,s.reps));return {date:workout.completedAt,value:Math.max(0,...best)};})).filter((p)=>p.value>0);return {pattern,values};}),[state.history]);
  const tierItems=useMemo(()=>Object.values(state.progress).flatMap((progress)=>{const exercise=EXERCISE_BY_ID[progress.exerciseId];if(!exercise||exercise.progressionMode!=='tier'||exercise.tierIndex!==progress.tierIndex)return [];return [{progress,exercise}];}).slice(0,4),[state.progress]);
  if(!isPremium)return <SafeAreaView style={common.screen}/>;
  if(state.profile?.equipment==='bodyweight')return <SafeAreaView style={common.screen} edges={['top']}><ScrollView contentContainerStyle={common.page}><Text style={common.eyebrow}>PROGRESS</Text><Text style={common.h1}>Your movement tiers</Text><Text style={common.body}>Bodyweight progress is measured by harder, controlled variations—not estimated load.</Text>{tierItems.map(({progress,exercise})=>{const chain=exercise.tierChain??[exercise.id];const currentId=chain[progress.tierIndex]??exercise.id;return <View key={exercise.id} style={common.card}><Text style={s.cardTitle}>{PATTERN_LABELS[exercise.pattern]}</Text><Text style={s.current}>{EXERCISE_BY_ID[currentId]?.name??exercise.name}</Text><View style={s.tierTrack}>{chain.map((id,i)=><View key={id} style={[s.tierDot,i<=progress.tierIndex&&s.tierDotActive]}/>)}</View><Text style={s.muted}>Tier {progress.tierIndex+1} of {chain.length}</Text></View>})}</ScrollView></SafeAreaView>;
  return <SafeAreaView style={common.screen} edges={['top']}><ScrollView contentContainerStyle={common.page}><Text style={common.eyebrow}>STRENGTH CURVE</Text><Text style={common.h1}>Proof you are stronger.</Text><Text style={common.body}>Estimated 1-rep max uses the Epley formula from your best completed set. Trends matter more than any single point.</Text>{points.filter((x)=>x.values.length>0).map(({pattern,values})=><CurveCard key={pattern} title={PATTERN_LABELS[pattern]} values={values.map((v)=>v.value)}/>)}{state.history.length===0?<View style={common.card}><Text style={s.cardTitle}>Your first point starts today</Text><Text style={common.body}>Complete a loaded session and your strength curve will appear here.</Text></View>:null}</ScrollView></SafeAreaView>;
}
function CurveCard({title,values}:{title:string;values:number[]}){const max=Math.max(...values);const min=Math.min(...values);const range=Math.max(1,max-min);const first=values[0]??0;const last=values.at(-1)??0;const gain=values.length>1?last-first:0;return <View style={common.card}><View style={s.row}><View><Text style={s.cardTitle}>{title}</Text><Text style={s.big}>{last.toFixed(1)} kg</Text></View><Text style={[s.gain,gain<0&&{color:colors.danger}]}>{gain>=0?'+':''}{gain.toFixed(1)} kg</Text></View><View style={s.chart}>{values.map((value,i)=><View key={i} style={s.barSlot}><View style={[s.bar,{height:18+((value-min)/range)*62}]}/></View>)}</View><Text style={s.muted}>{values.length} session point{values.length===1?'':'s'} · e1RM</Text></View>}
const s=StyleSheet.create({row:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},cardTitle:{fontSize:16,fontWeight:'800',color:colors.ink},big:{fontSize:26,fontWeight:'900',color:colors.ink,marginTop:5},gain:{color:colors.green,fontWeight:'900',fontSize:14,backgroundColor:colors.soft,paddingHorizontal:9,paddingVertical:6,borderRadius:10},chart:{height:90,flexDirection:'row',alignItems:'flex-end',gap:5,marginTop:14,borderBottomWidth:1,borderBottomColor:colors.line},barSlot:{flex:1,alignItems:'center',justifyContent:'flex-end'},bar:{width:'72%',maxWidth:22,backgroundColor:colors.green,borderTopLeftRadius:5,borderTopRightRadius:5},muted:{fontSize:12,color:colors.muted,marginTop:8},current:{fontSize:21,fontWeight:'900',color:colors.green,marginTop:6},tierTrack:{flexDirection:'row',gap:7,marginTop:16},tierDot:{flex:1,height:7,borderRadius:4,backgroundColor:colors.line},tierDotActive:{backgroundColor:colors.green}});
