import { Alert, Linking, Platform, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import * as WebBrowser from 'expo-web-browser';
import { resetOnboarding, usePremium } from '@app-factory/core';
import { Ionicons } from '@expo/vector-icons';
import { useApp } from '../../src/AppProvider';
import { common,colors } from '../../src/theme';
import { BrandMark } from '../../src/components';
import type { Joint } from '../../src/types';
import { generatePlan } from '../../src/engine';

const PRIVACY_URL='https://parphelie.com/ironhale/privacy';const TERMS_URL='https://www.apple.com/legal/internet-services/itunes/dev/stdeula/';
const MANAGE_URL=Platform.select({ios:'https://apps.apple.com/account/subscriptions',android:'https://play.google.com/store/account/subscriptions',default:'https://apps.apple.com/account/subscriptions'})!;
const labels:Record<Joint,string>={knee:'Knee',shoulder:'Shoulder',lumbar:'Lower back',hip:'Hip',wrist:'Wrist'};
export default function Settings(){const router=useRouter();const {state,update,reset}=useApp();const {isPremium,restore}=usePremium();const profile=state.profile;
  const onRestore=async()=>{try{const result=await restore();Alert.alert(result.isActive?'Purchases restored':'Nothing to restore');}catch{Alert.alert('Restore failed','Please try again.');}};
  const commitProfile=(next:NonNullable<typeof profile>)=>update((s)=>({...s,profile:next,plan:generatePlan(next,s.progress,s.plan[0]?.scheduledAt??s.createdAt)}));
  const toggle=(joint:Joint)=>profile&&commitProfile({...profile,flaggedJoints:profile.flaggedJoints.includes(joint)?profile.flaggedJoints.filter((j)=>j!==joint):[...profile.flaggedJoints,joint]});
  const resetAll=()=>Alert.alert('Reset IronHale?','This permanently deletes your local plan, workout history and preferences.',[{text:'Cancel',style:'cancel'},{text:'Delete everything',style:'destructive',onPress:()=>void (async()=>{await reset();await resetOnboarding();router.replace('/onboarding');})}]);
  const rows=[{icon:'refresh-outline',label:'Restore purchases',press:()=>void onRestore()},{icon:'card-outline',label:'Manage subscription',press:()=>void Linking.openURL(MANAGE_URL)},{icon:'shield-outline',label:'Privacy Policy',press:()=>void WebBrowser.openBrowserAsync(PRIVACY_URL)},{icon:'document-text-outline',label:'Terms of Use / EULA',press:()=>void WebBrowser.openBrowserAsync(TERMS_URL)}] as const;
  return <SafeAreaView style={common.screen} edges={['top']}><ScrollView contentContainerStyle={common.page}><View style={{flexDirection:'row',alignItems:'center',gap:12}}><BrandMark/><View><Text style={common.eyebrow}>IRONHALE</Text><Text style={common.h1}>Settings</Text></View></View>
    <View style={[common.card,s.plan]}><View><Text style={s.label}>YOUR PLAN</Text><Text style={s.planName}>{isPremium?'IronHale Premium':'6-session free plan'}</Text></View>{!isPremium?<TouchableOpacity style={s.upgrade} onPress={()=>router.push({pathname:'/paywall',params:{placement:'settings'}})}><Text style={s.upgradeText}>Go Premium</Text></TouchableOpacity>:<Ionicons name="checkmark-circle" size={30} color={colors.green}/>}</View>
    <View><Text style={s.section}>SENSITIVE JOINTS</Text><Text style={[common.body,{fontSize:13,marginBottom:10}]}>Permanent flags keep joint load at 0–1 whenever an alternative exists.</Text><View style={s.chips}>{(Object.keys(labels) as Joint[]).map((j)=>{const selected=profile?.flaggedJoints.includes(j);return <TouchableOpacity key={j} style={[s.chip,selected&&s.chipActive]} onPress={()=>toggle(j)}><Text style={[s.chipText,selected&&s.chipTextActive]}>{selected?'✓ ':''}{labels[j]}</Text></TouchableOpacity>})}</View></View>
    {profile?.temporaryFlags.filter((f)=>f.expiresAt>Date.now()).map((flag)=><View key={flag.joint} style={s.checkin}><View style={{flex:1}}><Text style={s.checkinTitle}>{labels[flag.joint]} check-in</Text><Text style={s.checkinBody}>Protected until {new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'}).format(new Date(flag.expiresAt))}</Text></View><TouchableOpacity onPress={()=>commitProfile({...profile,flaggedJoints:[...new Set([...profile.flaggedJoints,flag.joint])],temporaryFlags:profile.temporaryFlags.filter((f)=>f.joint!==flag.joint)})}><Text style={s.permanent}>Make permanent</Text></TouchableOpacity></View>)}
    {profile?.temporaryFlags.filter((f)=>f.expiresAt<=Date.now()).map((flag)=><View key={`expired-${flag.joint}`} style={[s.checkin,{flexDirection:'column',alignItems:'stretch'}]}><Text style={s.checkinTitle}>Is your {labels[flag.joint].toLowerCase()} feeling better?</Text><View style={s.checkActions}><TouchableOpacity style={s.checkButton} onPress={()=>commitProfile({...profile,temporaryFlags:profile.temporaryFlags.filter((f)=>f.joint!==flag.joint)})}><Text style={s.checkButtonText}>Yes</Text></TouchableOpacity><TouchableOpacity style={s.checkButton} onPress={()=>commitProfile({...profile,temporaryFlags:profile.temporaryFlags.map((f)=>f.joint===flag.joint?{...f,expiresAt:Date.now()+7*86400000}:f)})}><Text style={s.checkButtonText}>Still a bit</Text></TouchableOpacity><TouchableOpacity style={s.checkButton} onPress={()=>commitProfile({...profile,flaggedJoints:[...new Set([...profile.flaggedJoints,flag.joint])],temporaryFlags:profile.temporaryFlags.filter((f)=>f.joint!==flag.joint)})}><Text style={s.checkButtonText}>Permanent</Text></TouchableOpacity></View></View>)}
    <View style={s.group}>{rows.map((row)=><TouchableOpacity key={row.label} style={s.row} onPress={row.press}><Ionicons name={row.icon} size={20} color={colors.green}/><Text style={s.rowText}>{row.label}</Text><Ionicons name="chevron-forward" size={18} color={colors.muted}/></TouchableOpacity>)}</View>
    <View style={s.disclaimer}><Ionicons name="medical-outline" size={21} color={colors.orange}/><Text style={s.disclaimerText}>IronHale is not medical advice. Consult your doctor before starting a new training program.</Text></View>
    <TouchableOpacity style={s.reset} onPress={resetAll}><Text style={s.resetText}>Reset app and delete local data</Text></TouchableOpacity><Text style={s.version}>IronHale 1.0.0 · Data stays on this device</Text>
  </ScrollView></SafeAreaView>}
const s=StyleSheet.create({plan:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},label:{fontSize:10,fontWeight:'900',letterSpacing:1,color:colors.muted},planName:{fontSize:18,fontWeight:'900',color:colors.ink,marginTop:4},upgrade:{backgroundColor:colors.green,paddingHorizontal:13,paddingVertical:10,borderRadius:12},upgradeText:{color:'#fff',fontWeight:'800',fontSize:13},section:{fontSize:12,fontWeight:'900',letterSpacing:1.2,color:colors.ink,marginBottom:5},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,borderRadius:999,paddingHorizontal:13,paddingVertical:9},chipActive:{backgroundColor:colors.soft,borderColor:colors.green},chipText:{color:colors.muted,fontWeight:'700'},chipTextActive:{color:colors.green},checkin:{backgroundColor:'#FFF0E3',borderRadius:16,padding:15,flexDirection:'row',alignItems:'center',gap:10},checkinTitle:{fontWeight:'800',fontSize:15,color:colors.ink},checkinBody:{fontSize:12,color:colors.muted,marginTop:2},permanent:{fontSize:12,fontWeight:'800',color:colors.green},checkActions:{flexDirection:'row',gap:7},checkButton:{flex:1,backgroundColor:'#fff',borderRadius:10,paddingVertical:9,alignItems:'center'},checkButtonText:{fontSize:11,fontWeight:'800',color:colors.green},group:{backgroundColor:colors.surface,borderRadius:18,borderWidth:1,borderColor:colors.line,overflow:'hidden'},row:{height:58,paddingHorizontal:16,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.line},rowText:{flex:1,fontSize:15,fontWeight:'700',color:colors.ink},disclaimer:{backgroundColor:'#FFF5EC',borderRadius:16,padding:15,flexDirection:'row',gap:10},disclaimerText:{flex:1,fontSize:12,lineHeight:18,color:'#74533B'},reset:{padding:14,alignItems:'center'},resetText:{color:colors.danger,fontWeight:'700',fontSize:13},version:{textAlign:'center',fontSize:11,color:colors.muted}});
