import { useEffect, useMemo, useRef, useState } from 'react';
import { Animated, Easing, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { OnboardingFlow, setOnboardingComplete, type OnboardingStep } from '@app-factory/core';
import { Ionicons } from '@expo/vector-icons';
import { BrandMark, Choice } from '../src/components';
import { useApp } from '../src/AppProvider';
import { useT } from '../src/i18n';
import { colors } from '../src/theme';
import type { EquipmentProfile, Joint, Profile, SkillTier } from '../src/types';

const wait=(ms:number)=>new Promise<void>((resolve)=>setTimeout(resolve,ms));

function StepIcon({name}:{name:React.ComponentProps<typeof Ionicons>['name']}){
  return <View style={s.iconWrap}><Ionicons name={name} size={27} color={colors.green}/></View>;
}

/** SPEC §3: the medical disclaimer must be shown before the first onboarding step. */
function DisclaimerNote({text}:{text:string}){
  return <View style={s.disclaimer}><Ionicons name="medical-outline" size={17} color={colors.orange}/><Text style={s.disclaimerText}>{text}</Text></View>;
}

export default function Onboarding(){
  const router=useRouter(); const {finishOnboarding}=useApp();
  const t=useT();
  const [goal,setGoal]=useState<Profile['goal']>(); const [ageBand,setAge]=useState<string>();
  const [joints,setJoints]=useState<Joint[]>([]); const [none,setNone]=useState(false);
  const [equipment,setEquipment]=useState<EquipmentProfile>(); const [skillTier,setSkill]=useState<SkillTier>(); const [days,setDays]=useState<2|3|4>();
  const toggleJoint=(joint:Joint)=>{setNone(false);setJoints((all)=>all.includes(joint)?all.filter((j)=>j!==joint):[...all,joint]);};
  const profile:Profile|undefined=goal&&ageBand&&equipment&&skillTier&&days?{goal,ageBand,equipment,skillTier,daysPerWeek:days,flaggedJoints:joints,temporaryFlags:[]}:undefined;
  const adapted = profile ? (joints.includes('knee') ? t.onboarding.reveal.adaptKnee : joints.includes('shoulder') ? t.onboarding.reveal.adaptShoulder : joints.includes('lumbar') ? t.onboarding.reveal.adaptLumbar : t.onboarding.reveal.adaptDefault) : '';

  const steps=useMemo<OnboardingStep[]>(()=>[
    {id:'goal',title:t.onboarding.goal.title,description:t.onboarding.goal.description,canContinue:!!goal,content:<View style={{width:'100%',gap:10}}><View style={{alignItems:'center'}}><BrandMark size={58}/></View><Choice label={t.onboarding.goal.strong} selected={goal==='strong'} onPress={()=>setGoal('strong')}/><Choice label={t.onboarding.goal.independent} selected={goal==='independent'} onPress={()=>setGoal('independent')}/><Choice label={t.onboarding.goal.muscle} selected={goal==='muscle'} onPress={()=>setGoal('muscle')}/><DisclaimerNote text={t.onboarding.disclaimer}/></View>},
    {id:'age_band',title:t.onboarding.age.title,description:t.onboarding.age.description,canContinue:!!ageBand,content:<View style={{width:'100%',gap:8}}><StepIcon name="hourglass-outline"/>{['50–54','55–59','60–64','65–69','70+'].map((x)=><Choice key={x} label={x} selected={ageBand===x} onPress={()=>setAge(x)}/>)}</View>},
    {id:'joints',title:t.onboarding.joints.title,description:t.onboarding.joints.description,canContinue:true,content:<View style={{width:'100%',gap:8}}><StepIcon name="shield-checkmark-outline"/>{(Object.keys(t.joints) as Joint[]).map((j)=><Choice key={j} label={t.joints[j]} selected={joints.includes(j)} onPress={()=>toggleJoint(j)}/>)}<Choice label={t.onboarding.joints.none} selected={none} onPress={()=>{setNone(true);setJoints([]);}}/></View>},
    {id:'equipment',title:t.onboarding.equipment.title,description:t.onboarding.equipment.description,canContinue:!!equipment,content:<View style={{width:'100%',gap:10}}><StepIcon name="barbell-outline"/><Choice label={t.onboarding.equipment.gym} detail={t.onboarding.equipment.gymDetail} selected={equipment==='gym'} onPress={()=>setEquipment('gym')}/><Choice label={t.onboarding.equipment.home} detail={t.onboarding.equipment.homeDetail} selected={equipment==='home_dumbbells'} onPress={()=>setEquipment('home_dumbbells')}/><Choice label={t.onboarding.equipment.bodyweight} detail={t.onboarding.equipment.bodyweightDetail} selected={equipment==='bodyweight'} onPress={()=>setEquipment('bodyweight')}/></View>},
    {id:'experience',title:t.onboarding.experience.title,description:t.onboarding.experience.description,canContinue:!!skillTier,content:<View style={{width:'100%',gap:10}}><StepIcon name="trending-up-outline"/><Choice label={t.onboarding.experience.never} selected={skillTier===1} onPress={()=>setSkill(1)}/><Choice label={t.onboarding.experience.yearsAgo} selected={skillTier===2} onPress={()=>setSkill(2)}/><Choice label={t.onboarding.experience.current} selected={skillTier===3} onPress={()=>setSkill(3)}/></View>},
    {id:'days',title:t.onboarding.days.title,description:t.onboarding.days.description,canContinue:!!days,content:<View style={{width:'100%',gap:10}}><StepIcon name="calendar-outline"/>{([2,3,4] as const).map((n)=><Choice key={n} label={t.onboarding.days.perWeek(n)} detail={n===2?t.onboarding.days.detail72:t.onboarding.days.detail48} selected={days===n} onPress={()=>setDays(n)}/>)}</View>},
    {id:'building_plan',title:t.onboarding.building.title,description:t.onboarding.building.description,cta:t.onboarding.building.cta,canContinue:!!profile,onContinue:async()=>{if(profile){await wait(2800);await finishOnboarding(profile);}},content:<BuildingPlan steps={t.onboarding.building.steps}/>},
    {id:'plan_reveal',title:t.onboarding.reveal.title,description:t.onboarding.reveal.description,cta:t.onboarding.reveal.cta,canContinue:!!profile,content:<PlanReveal sessions={days??3} adapted={adapted} t={t.onboarding.reveal}/>},
  ],[adapted,ageBand,days,equipment,finishOnboarding,goal,joints,none,profile,skillTier,t]);

  return <OnboardingFlow steps={steps} primaryColor={colors.green} backgroundColor={colors.bg} textColor={colors.ink} mutedColor={colors.muted} backLabel={t.common.goBack} busyLabel={t.onboarding.buildingBusy} continueLabel={t.common.continue} onComplete={async()=>{await setOnboardingComplete();router.replace({pathname:'/paywall',params:{placement:'onboarding'}});}}/>;
}
function BuildingPlan({steps}:{steps:readonly string[]}){
  const pulse=useRef(new Animated.Value(.8)).current;
  const entries=useRef(steps.map(()=>new Animated.Value(0))).current;
  useEffect(()=>{const loop=Animated.loop(Animated.sequence([Animated.timing(pulse,{toValue:1.08,duration:850,easing:Easing.inOut(Easing.quad),useNativeDriver:true}),Animated.timing(pulse,{toValue:.8,duration:850,easing:Easing.inOut(Easing.quad),useNativeDriver:true})]));loop.start();Animated.stagger(260,entries.map((value)=>Animated.spring(value,{toValue:1,tension:70,friction:9,useNativeDriver:true}))).start();return()=>loop.stop();},[entries,pulse]);
  return <View style={s.builder}><View style={s.builderVisual}><Animated.View style={[s.builderHalo,{transform:[{scale:pulse}]}]}/><View style={s.builderCore}><Ionicons name="sparkles" size={28} color={colors.lime}/></View></View><View style={s.builderSteps}>{steps.map((text,index)=><Animated.View key={text} style={[s.builderStep,{opacity:entries[index]!,transform:[{translateY:entries[index]!.interpolate({inputRange:[0,1],outputRange:[10,0]})}]}]}><View style={s.builderCheck}><Ionicons name="checkmark" size={14} color="#fff"/></View><Text style={s.builderText}>{text}</Text></Animated.View>)}</View></View>;
}

function PlanReveal({sessions,adapted,t}:{sessions:number;adapted:string;t:ReturnType<typeof useT>['onboarding']['reveal']}){
  const entrance=useRef(new Animated.Value(0)).current;const details=useRef([new Animated.Value(0),new Animated.Value(0),new Animated.Value(0)]).current;const celebrate=useRef(new Animated.Value(0)).current;
  useEffect(()=>{Animated.sequence([Animated.spring(entrance,{toValue:1,tension:52,friction:7,useNativeDriver:true}),Animated.parallel([Animated.timing(celebrate,{toValue:1,duration:650,easing:Easing.out(Easing.cubic),useNativeDriver:true}),Animated.stagger(150,details.map((value)=>Animated.spring(value,{toValue:1,tension:65,friction:9,useNativeDriver:true})))])]).start();},[celebrate,details,entrance]);
  return <View style={s.reveal}><Animated.View pointerEvents="none" style={[s.spark,s.sparkLeft,{opacity:celebrate,transform:[{translateY:celebrate.interpolate({inputRange:[0,1],outputRange:[18,-6]})},{rotate:'-16deg'}]}]}><Ionicons name="sparkles" size={24} color={colors.orange}/></Animated.View><Animated.View pointerEvents="none" style={[s.spark,s.sparkRight,{opacity:celebrate,transform:[{translateY:celebrate.interpolate({inputRange:[0,1],outputRange:[18,-12]})},{rotate:'18deg'}]}]}><Ionicons name="sparkles" size={20} color={colors.green}/></Animated.View><Animated.View style={[s.planHero,{opacity:entrance,transform:[{scale:entrance.interpolate({inputRange:[0,1],outputRange:[.88,1]})}]}]}><View style={s.readyBadge}><Ionicons name="checkmark" size={23} color={colors.ink}/></View><View style={s.heroTop}><View style={s.heroIcon}><Ionicons name="calendar-outline" size={22} color={colors.lime}/></View><Text style={s.heroLabel}>{t.weekOne}</Text></View><Text style={s.heroSessions}>{t.sessionSummary(sessions)}</Text><View style={s.weekBars}>{Array.from({length:sessions},(_,index)=><View key={index} style={s.weekBar}><Ionicons name="barbell" size={14} color={colors.green}/></View>)}</View></Animated.View><Animated.View style={[s.adaptation,{opacity:details[0]!,transform:[{translateY:details[0]!.interpolate({inputRange:[0,1],outputRange:[16,0]})}]}]}><View style={s.adaptationIcon}><Ionicons name="shield-checkmark" size={20} color={colors.green}/></View><View style={{flex:1}}><Text style={s.adaptationLabel}>{t.eyebrow}</Text><Text style={s.adaptationText}>{adapted}</Text></View></Animated.View><Animated.View style={[s.promise,{opacity:details[1]!}]}><Ionicons name="trending-up" size={19} color={colors.green}/><Text style={s.promiseText}>{t.addLoad}</Text></Animated.View><Animated.View style={[s.effort,{opacity:details[2]!}]}><Ionicons name="hand-left-outline" size={18} color={colors.orange}/><Text style={s.effortText}>{t.rirNote}</Text></Animated.View></View>;
}
const s=StyleSheet.create({iconWrap:{alignSelf:'center',width:56,height:56,borderRadius:18,backgroundColor:colors.soft,alignItems:'center',justifyContent:'center',marginBottom:2},disclaimer:{marginTop:6,backgroundColor:'#FFF5EC',borderRadius:14,padding:13,flexDirection:'row',gap:9,alignItems:'flex-start'},disclaimerText:{flex:1,fontSize:13,lineHeight:19,fontWeight:'600',color:'#67462F'},builder:{width:'100%',backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,borderRadius:22,padding:18,gap:18},builderVisual:{height:82,alignItems:'center',justifyContent:'center'},builderHalo:{position:'absolute',width:72,height:72,borderRadius:36,backgroundColor:'#DCECCB'},builderCore:{width:54,height:54,borderRadius:18,backgroundColor:colors.green,alignItems:'center',justifyContent:'center'},builderSteps:{gap:10},builderStep:{flexDirection:'row',alignItems:'center',gap:10},builderCheck:{width:24,height:24,borderRadius:12,backgroundColor:colors.green,alignItems:'center',justifyContent:'center'},builderText:{flex:1,color:colors.ink,fontSize:14,lineHeight:19,fontWeight:'700'},reveal:{width:'100%',gap:13,position:'relative'},spark:{position:'absolute',zIndex:4},sparkLeft:{left:-5,top:-18},sparkRight:{right:2,top:-10},planHero:{backgroundColor:colors.ink,borderRadius:24,padding:20,gap:11,overflow:'hidden',shadowColor:colors.green,shadowOpacity:.22,shadowRadius:18,shadowOffset:{width:0,height:9},elevation:6},readyBadge:{position:'absolute',right:17,top:17,width:37,height:37,borderRadius:19,backgroundColor:colors.lime,alignItems:'center',justifyContent:'center'},heroTop:{flexDirection:'row',alignItems:'center',gap:9},heroIcon:{width:38,height:38,borderRadius:12,backgroundColor:'#2C4134',alignItems:'center',justifyContent:'center'},heroLabel:{color:colors.lime,fontSize:13,fontWeight:'900',letterSpacing:1.2},heroSessions:{color:'#fff',fontSize:25,lineHeight:31,fontWeight:'900',letterSpacing:-.6,paddingRight:28},weekBars:{flexDirection:'row',gap:7,marginTop:2},weekBar:{height:30,flex:1,borderRadius:9,backgroundColor:colors.lime,alignItems:'center',justifyContent:'center'},adaptation:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,borderRadius:18,padding:16,flexDirection:'row',gap:11,alignItems:'flex-start'},adaptationIcon:{width:38,height:38,borderRadius:12,backgroundColor:colors.soft,alignItems:'center',justifyContent:'center'},adaptationLabel:{fontSize:12,fontWeight:'900',letterSpacing:1,color:colors.green},adaptationText:{fontSize:17,lineHeight:23,fontWeight:'800',color:colors.ink,marginTop:4},promise:{flexDirection:'row',gap:9,alignItems:'flex-start',paddingHorizontal:5},promiseText:{flex:1,color:colors.ink,fontSize:16,lineHeight:23,fontWeight:'800'},effort:{backgroundColor:'#FFF4E8',borderRadius:14,padding:14,flexDirection:'row',gap:9,alignItems:'flex-start'},effortText:{flex:1,color:'#72523A',fontSize:15,lineHeight:22,fontWeight:'600'}});
